name: Send repository dispatch event

on:
  workflow_dispatch:
  push:
    branches:
      - main

# Article: How to trigger a GitHub action workflow in another repository
# https://dev.to/ngnijland/how-to-trigger-a-github-action-workflow-in-another-repository-k3k
# Create a repository dispatch event from the Source Repository
# https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event
# Repository Dispatch to `repository_dispatch` on the Target Repository
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch
# Need to Get and Renew a Personal Access Token (Classic) with all Repo permissions.
# Old: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
#
# Updates 2025-08-17
# https://docs.github.com/en/actions/how-tos/write-workflows/choose-when-workflows-run/trigger-a-workflow?search-overlay-input=repository_dispatch&search-overlay-ask-ai=true
# Now using ${{ secrets.GITHUB_TOKEN }}

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    steps:
      - name: Fire event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/boseji/-1/dispatches \
            -d '{"event_type":"dispatch-event","client_payload": {"message": "scratch-docs trigger repository!"}}'
